<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DocumentationFile>bin\Debug\LasseVK.Console.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\LasseVK.Console.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="Ansi\AnsiWriter.Cursor.cs">
        <DependentUpon>AnsiWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Ansi\AnsiWriter.Rendering.cs">
        <DependentUpon>AnsiWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Ansi\AnsiStringBuilder.cs">
        <DependentUpon>AnsiWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Ansi\AnsiTextWriter.cs">
        <DependentUpon>AnsiWriter.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
