<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="Ansi\AnsiWriter.Cursor.cs">
        <DependentUpon>AnsiWriter.cs</DependentUpon>
      </Compile>
      <Compile Update="Ansi\AnsiWriter.Rendering.cs">
        <DependentUpon>AnsiWriter.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
